[package]
name = "rxrust"
version = "0.7.2"
authors = ["adoo <Adoo@outlook.com>"]
edition = "2018"
description = "A Rust implementation of Reactive Extensions."
keywords = ["reactivex", "rx", "frp"]
license = "MIT"

[package.metadata.release]
no-dev-version = false

[dependencies]
futures-preview = "=0.3.0-alpha.18"
lazy_static = "1.3.0"
futures-timer = "0.3.0"
smallvec = "1.1.0"

[dev-dependencies]
float-cmp = "0.5.3"
